#ifndef OUTTYPE_HINCLUDED
#define OUTTYPE_HINCLUDED

#include "pkd.h"

enum outtype_arraytype {
	OUT_NULL,
	OUT_COLOR_ARRAY,
	OUT_DENSITY_ARRAY,
	OUT_POT_ARRAY,
	OUT_AMAG_ARRAY,
	OUT_IMASS_ARRAY,
	OUT_RUNG_ARRAY,
#ifdef GASOLINE
	OUT_U_ARRAY,
	OUT_HSMDIVV_ARRAY,
#ifndef NOCOOLING
	OUT_UDOT_ARRAY,
	OUT_COOL_ARRAY0,
	OUT_COOL_ARRAY1,
	OUT_COOL_ARRAY2,
#endif
	OUT_BALSARASWITCH_ARRAY,
	OUT_DIVV_ARRAY,
	OUT_MUMAX_ARRAY,
	OUT_SHOCKTRACKER_ARRAY,
	OUT_DIVONCONH_ARRAY,
	OUT_DIVONCONX_ARRAY,
	OUT_DIVRHOV_ARRAY,
	OUT_PDV_ARRAY,
	OUT_PDVPRES_ARRAY,
	OUT_PDVVISC_ARRAY,
	OUT_PDVSN_ARRAY,
	OUT_USN_ARRAY,
#endif
	OUT_SOFT_ARRAY,
	OUT_IORDER_ARRAY,
	OUT_IGASORDER_ARRAY,
	OUT_TCOOLAGAIN_ARRAY,
	OUT_MSTAR_ARRAY,
	OUT_H_ARRAY,
	OUT_DT_ARRAY,
#ifdef COLLISIONS
	OUT_REJECTS_ARRAY
#endif
	};

enum outtype_vectortype {
	OUT_POS_VECTOR,
	OUT_VEL_VECTOR,
	OUT_ACCEL_VECTOR,
#ifdef NEED_VPRED
	OUT_VPRED_VECTOR,
	OUT_GRADRHO_VECTOR,
	OUT_ACCELPRES_VECTOR,
#endif
	OUT_RFORM_VECTOR,
	OUT_VFORM_VECTOR
	};

void pkdOutArray(PKD,char *,int,int);
void pkdOutVector(PKD,char *,int,int,int);

#endif
